// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  navbar: dynamic(() => import("./Navbar")),
  rich_text: dynamic(() => import("./RichText")),
};
